### ISSUE TITLE
请问test的时候为什么feature不需要用VGG提取而是直接使用generator网络呢？

### ISSUE THREAD

**Issue by Drow999** [wan-h/AnimeGAN_pytorch#4]
原作者tensorflow版本的代码里也是这样，VGG用作了loss的计算但是在训练时图片都是直接给到generator和discriminator的，不经过VGG，测试也是直接把图片给generator就生成了动漫图片

**Comment by wan-h** [comment]
因为style-loss计算是为了计算图片之间的风格差异, 风格差异一般使用gram矩阵表示, 所以:
1. 使用VGG获取图片的特征图(这里不是使用的原图)
2. 然后计算两张图片的Gram矩阵
3. 再用计算得到的Gram矩阵计算l1_loss表示风格差异
这个vgg只是为了算style-loss的时候使用, 和G网络的推理是没有任何关系的, 只作用于训练时G网络的输出用于计算和真实图片之间的style-loss

**Comment by wan-h** [comment]
因为style-loss计算是为了计算图片之间的风格差异, 风格差异一般使用gram矩阵表示, 所以:
1. 使用VGG获取图片的特征图(这里不是使用的原图)
2. 然后计算两张图片的Gram矩阵
3. 再用计算得到的Gram矩阵计算l1_loss表示风格差异
这个vgg只是为了算style-loss的时候使用, 和G网络的推理是没有任何关系的, 只作用于训练时G网络的输出用于计算和真实图片之间的style-loss
