### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by zhiqiangohuo** [wan-h/AnimeGAN_pytorch#5]
您好，我下载了dataset.zip  然而并没有找到您发布的样例中的  real文件夹，想问一下 是需要什么提前预处理的策略吗？

**Comment by wan-h** [comment]
这个文件夹我做了一下整理，为了方便训练，所有相对原作者的结构有一些改动，但是内容都是一致的













在 2023-03-24 19:27:48，"zhiqiangohuo" ***@***.***> 写道：

您好，我下载了dataset.zip 然而并没有找到您发布的样例中的 real文件夹，想问一下 是需要什么提前预处理的策略吗？
